### ISSUE TITLE
ox:Trunk-bone dont work on ox_inventory and up 2.34.0 

### ISSUE THREAD

**Issue by stone9k** [Sleepless-Development/sleepless_interact#10]
The default "addGlobalVehicle" that uses 'ox:Trunk'  uses a function that was removed from ox_inventory a while back (2.34.0). So, the trunk is always at the rear of the car. I have tried to make a fix but lack the necessary knowledge of ox to find a good solution.
[GitHub Commit:refactor(client/inventory): ignore door validation for bone overrides](https://github.com/overextended/ox_inventory/commit/bf69a767d3db9b5250c68d5f5cf9ccb9c7467faf)

**Comment by DemiAutomatic** [comment]
This has been tested much more recently than 2.34.0 and was working fine.

**Comment by stone9k** [comment]
https://github.com/Sleepless-Development/sleepless_interact/blob/main/imports/utils.lua#L340
This is refering to something that dont exist in ox_inventory anymore. And it is defenetly not working to define the trunk to any bone when using "ox:Trunk" as id on a interact. Its allways on the rear, nomatter what.
Its working like it should when not using "ox:Trunk" as id.

**Comment by stone9k** [comment]
Tested on Nero

**Comment by DemiAutomatic** [comment]
![image](https://github.com/user-attachments/assets/f0e582b9-aea1-48cb-89ba-40683034eb6b)
![image](https://github.com/user-attachments/assets/c82b1cae-9d23-4701-b832-a9d966c3cc78)
![image](https://github.com/user-attachments/assets/0eb25397-a63f-49d3-b563-2c1c90b354fc)
![image](https://github.com/user-attachments/assets/359a0cef-ea1c-45c3-9d0c-c9ffafc46d50)


unless im misunderstanding is this not the expected behavior?

**Comment by stone9k** [comment]
Im not getting the same behavior. So i guess there's another problem om my end causing this. 
I'm so sorry for the inconvenience, and thanks for your time.
